name: Build sitemap

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    env:
      BASE_URL: https://saipratheekbanda.com

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate sitemap.xml
        run: |
          python - << 'PY'
          from pathlib import Path
          from datetime import datetime, timezone
          from xml.dom import minidom
          import os, xml.etree.ElementTree as ET

          BASE_URL = os.environ.get("BASE_URL","").rstrip("/") or "https://saipratheekbanda.com"
          ROOT = Path.cwd()

          html_files = sorted(ROOT.glob("*.html"))
          pdf_files  = sorted((ROOT / "assets").rglob("*.pdf")) if (ROOT / "assets").exists() else []
          files = html_files + pdf_files

          def add_url(parent, loc, lastmod=None, changefreq=None, priority=None):
              u = ET.SubElement(parent, "url")
              ET.SubElement(u, "loc").text = loc
              if lastmod: ET.SubElement(u, "lastmod").text = lastmod
              if changefreq: ET.SubElement(u, "changefreq").text = changefreq
              if priority: ET.SubElement(u, "priority").text = priority

          urlset = ET.Element("urlset", xmlns="http://www.sitemaps.org/schemas/sitemap/0.9")
          # Home
          add_url(urlset, f"{BASE_URL}/", changefreq="weekly", priority="1.0")

          for p in files:
              rel = "/" + str(p.relative_to(ROOT)).replace("\\", "/")
              ts = datetime.fromtimestamp(p.stat().st_mtime, tz=timezone.utc).strftime("%Y-%m-%d")
              pr = "0.7" if p.suffix.lower()==".html" else "0.5"
              add_url(urlset, f"{BASE_URL}{rel}", lastmod=ts, changefreq="monthly", priority=pr)

          rough = ET.tostring(urlset, encoding="utf-8")
          pretty = minidom.parseString(rough).toprettyxml(indent="  ", encoding="utf-8")
          Path("sitemap.xml").write_bytes(pretty)
          print("Wrote sitemap.xml")
          PY

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/update-sitemap
          commit-message: "chore: update sitemap [skip ci]"
          title: "chore: update sitemap"
          body: "Automated sitemap update generated by GitHub Actions."
          labels: automation
